### ISSUE TITLE
'deb-src' URIs in your sources.list

### ISSUE THREAD

**Issue by stappersg** [CumulusNetworks/DUE#11]
What happened:
```
$ debcheckout foo
E: You must put some 'deb-src' URIs in your sources.list
unknown package 'foo'
$ 
```

I see two options to make `debcheckout` possible:
1:  Copy apt sources list from  host
2:  Add  the  `deb-src`  in   sources.list

Option 1 has the advantage that you copy / clone  what the developer already has configured on the host. It supports local configuration.

**Comment by stappersg** [comment]
Option 1 implementation proposal:
```
--- a/libdue
+++ b/libdue
@@ -1076,6 +1076,11 @@ function fxnDoLogin()
         # If not otherwise specified
         # make sure the container mounts something local
 
+        #
+        # inherent apt sources from the host
+        # 
+        ADDITIONAL_MOUNTS+=" --volume /etc/apt:/etc/apt"
+
         #
         # Local filesystems the container can mount.
         #
```

**Comment by ehdoyle** [comment]
Ah. So here this gets trickier.
I can see that being an expected behavior, so it will definitely need to be addressed.

The origin of the problem is that base containers I'm pulling don't have active deb-src entries in their sources.list files, and this seems to be pretty standard for docker images( see examples below)

Possible solution:
 providing an --enable-deb-src flag on container creation that would parse the sources.list, uncomment any deb-src entries,
 and/or try to generate them by copying a deb line and starting it with deb-src.
 That does leave the possibility of generating bad entries, though.

Things to worry about:
I'd shy away from copying the host sources.list as that would create problems if there's a release difference, like a buster host using a Jessie container (or Ubuntu)

There's also the case of wanting to supplement with a local repository that might collide. At Cumulus we have internal repositories where there are locally patched versions of packages where we don't want the upstream source coming in, and override it in DUE
by replacing the /etc/apt/sources.list file with an empty file, and placing sources.list files for our local repositories under /etc/apt/sources.list.d 
( The templates creation moves existing container files into a cached area and puts any supplied files in their place)
The closest example to this in the existing code is using stretch-backports in ONIE )
https://github.com/CumulusNetworks/DUE/blob/master/templates/onie/filesystem/etc/apt/sources.list.d/stretch-backports.list

Thoughts?

Container sources list files: 

Here's sid:
# deb http://snapshot.debian.org/archive/debian/20200607T000000Z sid main
deb http://deb.debian.org/debian sid main

And part of an Ubuntu 18.04
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://archive.ubuntu.com/ubuntu/ bionic main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ bionic main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted

**Comment by stappersg** [comment]
On Sat, Aug 01, 2020 at 03:34:30PM -0700, Alex Doyle wrote:
> ... as that would create problems if there's a release difference, like a buster host using a Jessie container (or Ubuntu)
> 
> Thoughts?

sources.list has SEVERAL things:
 * "location"
 * "release"
 * besides 'deb' also  'deb-src'


When I proposed `ADDITIONAL_MOUNTS+=" --volume /etc/apt:/etc/apt"`
I forgot about "release", I was way to happy with having deb-src included
and my local apt repository as "location".


Rethinking the "What happened"
```
$ debcheckout foo
E: You must put some 'deb-src' URIs in your sources.list
unknown package 'foo'
$ 
```

It is probably more wise to do the `debcheckout` on the host,
not in a DUE environment. It solves the problem of the missing "deb-src"

**Comment by stappersg** [comment]
>  It is probably more wise to do the `debcheckout` on the host, not in a DUE environment. It solves the problem of the missing "deb-src"

So closing the issue.
