### ISSUE TITLE
mention systemd-binfmt / prefer it over binfmt-support

### ISSUE THREAD

**Issue by mbiebl** [CumulusNetworks/DUE#39]
Looking at the debian package, I see
```
$ grep binfmt-support -R
libdue:RECOMMENDED_PACKAGES=" binfmt-support qemu qemu-user-static "
debian/control:Recommends: binfmt-support, qemu, qemu-user-static
docs/Troubleshooting.md:`sudo apt update ; sudo apt install docker.io git rsync binfmt-support qemu qemu-user-static`  
docs/Troubleshooting.md:`binfmt-support` not being configured to handle ARM binaries. Ideally, qemu should register
docs/Troubleshooting.md:the architectures it can run with binfmt-support, so that when non-native code is encountered,
docs/Troubleshooting.md:`sudo apt update ; sudo apt install qemu qemu-user-static binfmt-support`
docs/Troubleshooting.md:which should have configured binfmt-support to have the entries. I had to do this on one system, 
docs/Troubleshooting.md:Restart binfmt-support  
docs/Troubleshooting.md:`sudo systemctl restart binfmt-support.service` 
```

systemd provides a builtin, cross-distro facility named systemd-binfmt to
register binary formats.

You can read more about it at
https://www.freedesktop.org/software/systemd/man/systemd-binfmt.html
https://www.freedesktop.org/software/systemd/man/binfmt.d.html
https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html

qemu in sid and bookworm ships binfmt.d configs, which means,  installing binfmt-support explicitly is no longer necessary.
The docs should be updated to reflect that.

**Comment by ehdoyle** [comment]
Thanks for pointing that out  - I'll leave this open to make sure that gets handled as part of the next release to be upstreamed.

**Comment by ehdoyle** [comment]
Hi - I'm finally getting around to following up on this as part of next release preparations.
I've updated the Troubleshooting document to point out that systemd-binfmt may not be needed if the host system is new enough to provide binfmt-support. I've added the proposed changes to the Troubleshooting docs below.
Thoughts? Thanks!

diff --git a/docs/Troubleshooting.md b/docs/Troubleshooting.md
index 4ff0359..109d905 100644
--- a/docs/Troubleshooting.md
+++ b/docs/Troubleshooting.md
@@ -8,10 +8,12 @@ Copyright 2022,2023 Nvidia Corporation.  All rights reserved.
 ## Symptom: Docker (or Podman) isn't installed
 
 ### Installing Docker without a DUE .deb
-If you've downloaded DUE as source, install its dependencies by running:  
+If you've downloaded DUE as source, install its dependencies by running:
 `sudo apt update ; sudo apt install docker.io git rsync binfmt-support qemu qemu-user-static`    
   
-**Note:**  docker.io can be replaced with docker-ce, or podman.
+**Note 1:**  docker.io can be replaced with docker-ce, or podman.
+**Note 2:**  Newer host system distributions may provide the systemd-binfmt package to support
+              the execution of non-native binaries, so that the binfmt-support package is not explicitly needed.
 
 The last three packages there are optional, but necessary if you want to run alternate architectures.
 
@@ -94,7 +96,8 @@ If QEMU is properly and fully installed, DUE should be able to run containers
 of other architectures seamlessly
 If you're reading this, then you've found a seam and should file a bug at:
 [https://github.com/CumulusNetworks/DUE/issues](https://github.com/CumulusNetworks/DUE/issues)
-
+**Note** Be aware that newer host distributions may use systemd-binfmt to handle the running of non-native binaries,
+and as a result, the following binfmt-support suggestions may or may not apply in your environment.
 
 ### Fails with: `standard\_init\_linux.go:211: exec user process caused "exec format error"`
 So far this has been the only time I've seen this die, and I tracked it down to my system's

**Comment by ehdoyle** [comment]
I'll push the change - feel free to reopen this or file another bug if I've missed the mark with this.  Thanks!
