### ISSUE TITLE
DUE create debian 8 gpg signatures invalid.

### ISSUE THREAD

**Issue by FadhliRais** [CumulusNetworks/DUE#41]
Hi...
im really new to this github and code thing, very sorry for my bad explanation and terrible english.

im trying to create debian 8 with DUE,
but alot of trouble I face.
from pre-install, and post install whole download package was error.

I think thats because the key is expired or invalid,
I have the change the code (pre install, commonlib, post install) to apply apt-key adv --recv-keys from debian8 repo,
and add another --force-yes to every apt-get install command.

maybe you can help another ppl to patch the code if they want to use debian 8.

the error is like this...

W: GPG error: http://deb.debian.org jessie-updates InRelease: The following signatures were invalid: KEYEXPIRED 1668891673
W: GPG error: http://deb.debian.org stretch-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9
W: GPG error: http://deb.debian.org jessie Release: The following signatures were invalid: KEYEXPIRED 1668891673

**Comment by ehdoyle** [comment]
Hi - thanks for pointing that out. Supporting older/expired distributions is one of those things DUE is explicitly designed to do, but  between the last release and this one keys have hit their expiration date, so this was a case DUE wasn't handling, but should  since this problem is going to affect more releases as time goes on, it's better to address it sooner than later.
I'm testing a patch now that uses apt --force-yes and  'faketime' with APT operations in pre-install, post-install and duebuild scripts to make things install, and reset the clock to 2017-01-01 for Debian 8 releases so that it doesn't realize the keys are expired.
I'm adding a mention of apt-key adv --recv-keys in the documentation and comments if users want to try that. I'd tried and got a different set of expired keys, but I'm sure there will be a window for later releases where that can be used instead of the 'faketime' solution.
Interestingly, APT doesn't error out with the key errors but returns '0'. 
When I push the fix, I'll reference this, so a fresh checkout of DUE should have it.

**Comment by ehdoyle** [comment]
Hm. Thought adding 'fixed' wouldn't = 'closed'.  Well, Debian 8 build image creation should be behaving itself now. Let me know if it works, and feel free to reopen this if it doesn't, or doesn't address the issues you were running in to.
