### ISSUE TITLE
problem with downloading efitools-1.9.2 

### ISSUE THREAD

**Issue by mrafatpanah** [CumulusNetworks/DUE#48]
Hi, I'm trying to create onie-debian-10 image using DUE but building failed due to can't finding efitools from this link:
https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git/snapshot/efitools-1.9.2.tar.gz
Please change this mirror link to a valid one in the post-install-config.sh.template file.

**Comment by ehdoyle** [comment]
Hi,
 Is the problem persisting? I just rebuilt successfully with:
./due  --create \
 --platform  linux/amd64\
  --name  onie-build-debian-10\
  --prompt  ONIE-10\
  --tag  onie-10\
  --use-template  onie\
   --from  debian:10\
   --description  'ONIE Build Debian 10'
   
   I was also able to wget 
   https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git/snapshot/efitools-1.9.2.tar.gz
   
   So it may be that the repository was just not accessible?

**Comment by mrafatpanah** [comment]
Hi,

Thank you for your prompt response!

I'm pleased to inform you that the issue has been resolved. I was able to successfully access the link today. Also build onie-build-debian-10 without any error. It seems that the problem was indeed related to the repository's accessibility.

Once again, I appreciate your quick assistance in resolving this matter.

**Comment by ehdoyle** [comment]
Glad to hear that. I'd initially thought this was an issue with the Debian 10 repository links needing to be updated as it is an older release ( I'd already had to do that with Debian 9 ), then realized it was an issue with pulling in source for the ONIE build. 
I'm just making a note of that here for when it eventually becomes a problem.
Thanks for confirming it was a connectivity issue. I'll close this out but feel free to reopen it if the issue seems to be coming back.
