### ISSUE TITLE
counter part of due  create

### ISSUE THREAD

**Issue by stappersg** [CumulusNetworks/DUE#9]
For what it is worth:  There is no counter part of `--create`

It might be as simple as  some _docker prune_ command, but please document it.

**Comment by stappersg** [comment]
I have no idea how much harm is done by posting this.
But it does _uncreate_ ...
```
$ docker image ls | grep ^due
due-pkg-sid                           pkg-sid             0d1808c44acb        23 hours ago        780MB
due-package-debian-10                 package-debian-10   c0605a322bf3        23 hours ago        730MB
$ docker image rm due-package-debian-10:package-debian-10
Untagged: due-package-debian-10:package-debian-10
Deleted: sha256:c0605a322bf3abdfdbc52dd57df3567a2ea8aff715bc856cf899303a54f29ba0
Deleted: sha256:ba1cabbf04c37074b5fc9620a429ce629784e0ff43d2a46b9655d1a9793f020b
Deleted: sha256:33b596a22b6e8bb63d9b0c11e5ef209ca76818bd99e86e4950f1c0c520d13aa0
Deleted: sha256:72dc80df4379c0add011c674d7befbe0c46079a1b2e76ad8e726cd5a1d73fe2d
Deleted: sha256:dadf5b3039990df76bb74da89d7b6d31e3bdb249c841b0f263f8928506af82cd
Deleted: sha256:0339602e0281a396742306d77bd2d35e1c880ef7be5bb920cc3e75c12b75e606
Deleted: sha256:07360e8f15fb552b685025fd2346fe6527b113827149cc3dafd60f97d523e0e5
Deleted: sha256:f01bd4b7be757f98190d6ab0614f6943325eaff99735588dda803e7fd1400c06
Deleted: sha256:d6635c4bd0b1c2769c589bee9f71af17ae35cf018f6e2991627510417f3865e9
Deleted: sha256:797cde7d241d6c74ba13772690518d0bd2e294ba1de9ec680eec56719305055d
Deleted: sha256:fe52863666d420ac407a2afedd1e2dc21fcce67bd092d4eacf5d328964cf350e
Deleted: sha256:10aa8aa15ae689a734301f4582bfb44e3291f1120089c20db6d2c6b996dd0f2c
Deleted: sha256:cd715cddc7f1f5ded8ed10ec4fd3859901b0a764f2f594fd09f4d6c58c3600d1
Deleted: sha256:a31b0b140c25f6ea73120f289c2b0e8421618f623d72218d719d03c2b6836eb6
Deleted: sha256:a2ed6f7b09ea7a9bd18f0d5e97b0c0b6c240aa5cff277a5b9faeab5f2871160b
$ docker image ls | grep ^due
due-pkg-sid                           pkg-sid             0d1808c44acb        23 hours ago        780MB
$ 
```

**Comment by ehdoyle** [comment]
The functionality for this is somewhat buried - under the --manage options there is a --delete-matched <term> option that will do a 
*term* match against existing images, then generate a delete-these-docker-images.sh script to delete them.

Given that this isn't immediately obvious, and isn't as straightforward as an 'rm', I'd agree that it needs to be more well advertised.

The reason for this implementation as script rather than command  was that I'm a bit wary of having destructive options being too fast, so having a two step process imposes a 'speed limit' to let the user consider what they're going to do,
and provides the option of selectively deleting images by editing the script rather than having to go one at a time or 
define a better filter.  I find it's particularly useful after a number of failed container creations finally succeed and I have a bunch of containers labeled <none> to toss.

Ex:
User: delete this
DUE: OK - here's a list of everything you wanted to delete - edit it, or not, but you're going to be the one pulling the trigger on this. I'm out. 
User: ./delete-these-docker-images.sh
( and...gone)

**Comment by stappersg** [comment]
On Sat, Aug 01, 2020 at 05:12:15PM -0700, Alex Doyle wrote:
> 
>  I'd agree that it needs to be more well advertised. 
> 

> 
> Example:
> User: delete this
> DUE: OK - here's a list of everything you wanted to delete - edit it, or not, but you're going to be the one pulling the trigger on this. I'm out. 
> User: ./delete-these-docker-images.sh
> ( and...gone)
> 

Technical:
The
> User: ./delete-these-docker-images.sh
should be
> User: sh ./delete-these-docker-images.sh


Educating the user:
> DUE: OK - here's a list of everything you wanted to delete - edit it, or not, but you're going to be the one pulling the trigger on this. I'm out. 
something like
> DUE: OK - here's a list of commands for what you wanted to delete, execute then to have the environments actually removed ...

**Comment by ehdoyle** [comment]
Hm. I could just add a --delete at the same parsing level as --create that then aliases to the creation of the delete script, and pad that out with a message on what the script is and how to use it? That would make it a bit more intuitive for the user to find the option, while still giving them a chance to think about what they are about to do?
